language: generic
matrix:
  include:

    - os: linux
      compiler: gfortran
      env: SOURCES=ubuntu-toolchain-r-test FORTRAN_COMPILER=gfortran-8 C_COMPILER=gcc-8 TRAVIS_COMPILER=gfortran
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           # compilers
            - gcc-8
            - gfortran-8
            - cmake
            # math libraries
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libopenblas-base
            - libopenblas-dev
            # other
            - doxygen

    - os: linux
      compiler: nvfortran
      env: SOURCES=ubuntu-toolchain-r-test FORTRAN_COMPILER=nvfortran C_COMPILER=pgcc TRAVIS_COMPILER=nvfortran
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           # compilers
            - cmake
            # math libraries
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libopenblas-base
            - libopenblas-dev
            # other
            - doxygen

    - os: osx
      osx_image: xcode10.2
      compiler: gfortran
      env: SOURCES=homebrew TRAVIS_COMPILER=gfortran
      addons:
        homebrew:
          packages:
            - m4
            - doxygen
          update: true

before_install:
  - mkdir gauopen
  - mkdir mqc-install
  - cd gauopen
  - wget http://gaussian.com/g16/gauopen_v2.zip
  - unzip gauopen_v2.zip
  - cd ..
  - which automake
  - autoconf --version
  - automake --version
  - if [ "${FORTRAN_COMPILER}" = "nvfortran" ]; then curl -s 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | /bin/sh; fi
  - if [ "${FORTRAN_COMPILER}" = "gfortran-8" ]; then fc=`which gfortran`; sudo rm `which gfortran`; sudo ln -s `which gfortran-8` $fc; fi
  - if [ "${C_COMPILER}" = "gcc-8" ]; then gc=`which gcc`; sudo rm `which gcc`; sudo ln -s `which gcc-8` $gc; fi
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${FORTRAN_COMPILER}" ]; then export FC="${FORTRAN_COMPILER}"; fi

install: 
  - |
    if [[ "${TRAVIS_COMPILER}" == "gfortran" ]]; then
       echo -e "yG$TRAVIS_BUILD_DIR/mqc-install\n-lblas\n-llapack\n$TRAVIS_BUILD_DIR/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile 
    elif [[ "${TRAVIS_COMPILER}" == "nvfortran" ]]; then
       echo -e "yP$TRAVIS_BUILD_DIR/mqc-install\n-lblas\n-llapack\n$TRAVIS_BUILD_DIR/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile 
    else 
      travis_terminate 1  
    fi

notifications:
  email: false
